server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy_msa?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
    show-sql: true
    generate-ddl: true
    database: mysql
    defer-datasource-initialization: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
greeting:
  message: Welcome to the Simple E-commerce.

token:
  expiration_time: 86400000
  secret: toy_mas_user_service_token_test

logging:
  level:
    org.toy.userservice: debug